### PR TITLE
Add fixer to convert QString `.arg` to python string `.format`

### PR DESCRIPTION
**Pull request by naufraghi**
Hi @cpascual,

we are migrating a large codebase, this is a fixer to convert QString.arg in python string.format.

Feel free to merge the fixer or not, I mainly like not to fragment the Qt related fixers.

Cheers,
Matteo

### CODE REVIEW

**Review by cpascual — COMMENTED** [review]
Hi,
Thanks a lot for contributing. I am happy to accept the PR, but, if it is not too much asking, would it be possible to get some example that documents this fixer?

Something similar to what I wrote in the README for the signals fixer...

**Comment by naufraghi** [comment]
Sure, I'll update the pull request as soon as possible.

**Comment by naufraghi** [comment]
Hi @cpascual, I added an example and a short intro in the README.

I renamed your example adding a `signal` suffix.

**Comment by cpascual** [comment]
Perfect.
Grazie mille!

**Pull request merged**
